### ISSUE TITLE
Inherit molecules in multiple displacements

### ISSUE THREAD

**Issue by w4bo** [AlchemistSimulator/Alchemist#17]
Instead of duplicating YAML code
```
displacements:
  - in:
      type: Point
      parameters: [44.137223, 12.241859]
    contents:
      - molecule: speed
        concentration: 0.2
  - in:
      type: Point
      parameters: [44.135522, 12.249264]
    contents:
      - molecule: speed
        concentration: 0.2
      - molecule: thr
        concentration: 0.2
```
it could be a good idea to provide support for "list anchoring" (see [here](http://stackoverflow.com/questions/9254178/is-there-yaml-syntax-for-sharing-part-of-a-list-or-map))
Something like (though the YAML syntax proposed here might be wrong):
```
molecules: &molecules
  - molecule: speed
    concentration: 0.2
displacements:
  - in:
      type: Point
      parameters: [44.137223, 12.241859]
    contents:
      * molecules
  - in:
      type: Point
      parameters: [44.135522, 12.249264]
    contents:
      * molecules
      - molecule: thr
        concentration: 0.2
```

**Comment by DanySK** [comment]
[This](http://yaml.org/type/merge.html) is presumably the specification. We should be supporting it already (If snakeyaml does), but it works only with mappings, while we want it to work with lists. We may want to say that mappings can be converted to lists (though [ordered mappings](http://yaml.org/type/omap.html) should be used to ensure reproducibility.

OR we could force the translation to target a SortedMap.

**Comment by DanySK** [comment]
Can you provide a code sample that you believe should work? Namely, a proper YAML that currently does not work in Alchemist, but would be a desiderata.

**Comment by metaphori** [comment]
I suggest taking a look here: https://github.com/yaml/yaml/issues/35

**Comment by DanySK** [comment]
This could be dealt with by processing lists of lists of `content`s as lists of `content`s (by flattening). Something similar is in place for reactions, where a list of list is expected: the management may be unified and simplified, in a backward compatible manner, by using this strategy.

**Comment by DanySK** [comment]
Also see [this reference](https://stackoverflow.com/questions/24090177/how-to-merge-yaml-arrays)

**Comment by DanySK** [comment]
Fixed on develop with the new loader. This is now supported via flattening:

```yaml
_molecules: &molecules
  - molecule: speed
    concentration: 0.2
displacements:
  - type: Point
    parameters: [44.137223, 12.241859]
    contents:
      * molecules
  - type: Point
    parameters: [44.135522, 12.249264]
    contents:
      - *molecules
      - molecule: thr
        concentration: 0.2
```

also, merge keys work, so the provided example can be solved even without flattening:

```yaml
_molecules: &molecules
  molecule: speed
  concentration: 0.2
displacements:
  - type: Point
    parameters: [44.137223, 12.241859]
    contents:
      * molecules
  - type: Point
    parameters: [44.135522, 12.249264]
    contents:
      - <<: *molecules
      - molecule: thr
        concentration: 0.2
```
