### ISSUE TITLE
String variables

### ISSUE THREAD

**Issue by w4bo** [AlchemistSimulator/Alchemist#18]
To run multiple Protelis simulations each with a different program, up to now I need to copy and paste my configuration changing only the program name (or creating a variable to create a binding number -> program).
```
# simulation 1
programs:
  - program: &program
    - time-distribution: 1
      program: distanceTo
    - program: send
displacements:
  - in:
      type: Point
      parameters: [44.137223, 12.241859]
    programs: 
      - *program


# simulation 2
programs:
  - program: &program
    - time-distribution: 1
      program: flex
    - program: send
displacements:
  - in:
      type: Point
      parameters: [44.137223, 12.241859]
    programs: 
      - *program
```
Having string variables might be useful in this case.
