### ISSUE TITLE
Fail to build `variables` if they are not declared using `formula`

### ISSUE THREAD

**Issue by nicolasfara** [AlchemistSimulator/Alchemist#2271]
Minimal running example of the bug:

```yaml
variables:
  max_lat: &max_lat 44.14795317094557
  min_lat: &min_lat 44.13340676305022
  max_lon: &max_lon 12.267570291912632
  min_lon: &min_lon 12.235568921311268
  city_poi: &city_poi 200
  latitude_space: &latitude_space
    formula: max_lat - min_lat
  longitude_space: &longitude_space
    formula: max_lon - min_lon
```
