### ISSUE TITLE
Not possible to reproduce GPS trace code from the web site

### ISSUE THREAD

**Issue by DenGuzawr22** [AlchemistSimulator/Alchemist#2821]
I get an error when I try to execute the GPS trace code showed on https://alchemistsimulator.github.io/howtos/simulation/deploy/gps/index.html :

```yaml
environment:
  type: OSMEnvironment
  parameters: ["vcm.pbf", false]

incarnation: sapere

_pools:
  - pool: &move
    - time-distribution: 0.1
      type: Event
      actions:
        - type: ReproduceGPSTrace
          parameters: ["gpsTrace", true, "AlignToSimulationTime"]

deployments:
  - type: FromGPSTrace
    parameters: [7, "gpsTrace", true, "AlignToSimulationTime"]
    programs:
      - *move
```
Error: `Exception in thread "main" java.lang.IllegalStateException: Invalid Deployment specification: {type=FromGPSTrace, parameters=[7, gpsTrace, true, AlignToSimulationTime], programs=[[{time-distribution=0.1, type=Event, actions=[{type=ReproduceGPSTrace, parameters=[gpsTrace, true, AlignToSimulationTime]}]}]]}`

Full Gradle console log: https://scans.gradle.com/s/lqmjb2rq5vyj2/console-log?anchor=132&page=1
Alchemist version: 26.0.13

With the latest version of Alchemist (28.4.4) I get similar error

Inserting `vcm.pbf` file in resource folder do not change the situation

### Hot to reproduce
1. Get a project that can run Alchemist tasks (Ex. https://github.com/DanySK/DisCoTec-2021-Tutorial).
2. In `src/main/yaml` add a new yaml file with code displayed above.
3. Execute the new task
