### ISSUE TITLE
CameraSee ignore nodes in its field of view

### ISSUE THREAD

**Issue by DenGuzawr22** [AlchemistSimulator/Alchemist#2873]
I tried to test CameraSee action but seems that it doesn't see the nodes in its field of view. 
Setup:
```yaml
incarnation: protelis
environment:
  type: ContinuousPhysics2DEnvironment
deployments:
  - type: SpecificPositions
    parameters: [[1,0],[1, 1], [0, 1], [-1,0], [0, -1], [-1, -1], [-1, 1], [1, -1]]
  - type: Point
    parameters: [0,0]
    programs:
      - type: Event
        time-distribution: 1
        actions:
          type: CameraSee
          parameters: [ 5.0, 90.0, "visibleNodes"]
      - type: Event
        time-distribution: 1
        actions:
          type: Spin
          parameters: [5.0]
```

The molecule list `visibleNodes` is always empty.

Repo with runnable example: https://github.com/DenGuzawr22/Reproducing-problem/tree/main

**Comment by DenGuzawr22** [comment]
The nodes can be visible only if they have a shape property. Example:
```yaml
...
 - type: SpecificPositions
    parameters: [[1,0],[1, 1], [0, 1], [-1,0], [0, -1], [-1, -1], [-1, 1], [1, -1]]
    properties:
      - type: CircularArea
 ...
 ```
