### ISSUE TITLE
Problem with project migration to new API

### ISSUE THREAD

**Issue by DenGuzawr22** [AlchemistSimulator/Alchemist#3047]
I try to migrate some parts of https://github.com/fedpet/Experiment-2019-Smartcam project to current Alchemist API and I get this problem:
_Exception in thread "main" java.lang.IllegalArgumentException: Unknown keys [time-distribution, conditions, actions] for the provided JavaType descriptor_

Full stacktrace:  https://scans.gradle.com/s/h22s5m6qnx7gu

yaml configuration:
```yaml
incarnation: protelis

variables:
  CameraSpeed: &CameraSpeed
    formula: 3
  EnvironmentSize: &EnvironmentSize
    type: ArbitraryVariable
    parameters: [500]
  FoVAngle: &FoVAngle
    formula: 60
  FoVDistance: &FoVDistance
    formula: 30
  RotationSpeed: &RotationSpeed
    formula: 36

environment:
  type: ContinuousPhysics2DEnvironment
deployments:
  - type: Point
    parameters: [10, 10]
    programs:
      - time-distribution: 2
        type: ChemicalReaction
        actions:
          - type: CameraSee
            parameters: [ *FoVDistance, *FoVAngle, vision ]
          - type: HeadTowardTarget
            parameters: [ heading, *RotationSpeed ]
          - type: MoveToTarget
            parameters: [ destination, *CameraSpeed ]
          - time-distribution: 2
            type: Event
            conditions:
              - type: MoleculeHasConcentration
                parameters: [ doZigZag, true ]
            actions:
              - type: ZigZagMove
                parameters: [ 999999, *CameraSpeed ]
      - time-distribution: 2
        type: Event
        conditions:
          - type: MoleculeHasConcentration
            parameters: [ doSpin, true ]
        actions:
          - type: Spin
            parameters: [ *RotationSpeed ]
      - time-distribution: 1
        program: ff_linpro
      - program: send
```

**Comment by DenGuzawr22** [comment]
Problem with indentation of:
```yaml
...
- time-distribution: 2
  type: Event
  conditions:
    - type: MoleculeHasConcentration
      parameters: [ doZigZag, true ]
  actions:
    - type: ZigZagMove
      parameters: [ 999999, *CameraSpeed ]
...
```
