### ISSUE TITLE
GUI problem: does not correctly show a grid of devices

### ISSUE THREAD

**Issue by metaphori** [AlchemistSimulator/Alchemist#73]
**On:** commit ab276ee (Alchemist 8.0.0)
**Verified absence on:** Alchemist 7.0.1 (plus commits from #72 )

When I start Alchemist with the following simulation configuration, I only see one node (or possibly all nodes located in a single point), instead of a grid of nodes.

```yaml
network-model:
  type: EuclideanDistance
  parameters: [2.0]

incarnation: scafi

positions:
  type: Continuous2DEuclidean

displacements:
- in:
    type: Grid
    parameters: [0, 0, 20, 20, 1, 1, 0.8, 0.8]
```
